### ISSUE TITLE
Search files lost sdk modules

### ISSUE THREAD

**Issue by zyuyou** [ignatov/intellij-erlang#1021]
- [IDEA-2023.2] no sdk modules
![image](https://github.com/ignatov/intellij-erlang/assets/1913492/7ba9aa74-86e6-4a81-a643-b1a43953de3d)

- [IDEA-2023.1] it should be like this
![image](https://github.com/ignatov/intellij-erlang/assets/1913492/bacdd128-b704-49d0-833f-a3b1f552e450)

- some erros in idea.log
```
2023-08-28 09:42:08,766 [326015129] SEVERE - #c.i.o.a.i.ApplicationImpl - 'other' has different root
java.lang.IllegalArgumentException: 'other' has different root
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:404)
	at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
	at com.intellij.searchEverywhereMl.ranking.features.SearchEverywhereFileFeaturesProvider.getRelativePathNameMatchingFeatures$intellij_searchEverywhereMl_ranking(SearchEverywhereFileFeaturesProvider.kt:153)
	at com.intellij.searchEverywhereMl.ranking.features.SearchEverywhereFileFeaturesProvider.getElementFeatures(SearchEverywhereFileFeaturesProvider.kt:79)
	at com.intellij.searchEverywhereMl.ranking.SearchEverywhereMlSearchState.getElementFeatures(SearchEverywhereMlSearchState.kt:41)
	at com.intellij.searchEverywhereMl.ranking.SearchEverywhereMlRankingService.createFoundElementInfo(SearchEverywhereMlRankingService.kt:75)
	at com.intellij.searchEverywhereMl.SearchEverywhereMlServiceImpl.createFoundElementInfo(SearchEverywhereMlServiceImpl.kt)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ResultsAccumulator.addElement(MixedResultsSearcher.java:296)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.processFoundItem(MixedResultsSearcher.java:224)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.lambda$run$0(MixedResultsSearcher.java:185)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$fetchWeightedElements$0(PSIPresentationBgRendererWrapper.java:68)
	at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.processElement(FileSearchEverywhereContributor.java:124)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$2(AbstractGotoSEContributor.java:252)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.lambda$processFiles$4(GotoFileItemProvider.java:424)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:814)
	at com.intellij.ide.actions.GotoFileItemProvider$SuffixMatches.processFiles(GotoFileItemProvider.java:426)
	at com.intellij.ide.actions.GotoFileItemProvider.processItemsForPattern(GotoFileItemProvider.java:111)
	at com.intellij.ide.actions.GotoFileItemProvider.doFilterElements(GotoFileItemProvider.java:83)
	at com.intellij.ide.actions.GotoFileItemProvider.lambda$filterElementsWithWeights$0(GotoFileItemProvider.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.actions.GotoFileItemProvider.filterElementsWithWeights(GotoFileItemProvider.java:64)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.lambda$fetchWeightedElements$5(AbstractGotoSEContributor.java:251)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.ide.actions.searcheverywhere.AbstractGotoSEContributor.fetchWeightedElements(AbstractGotoSEContributor.java:277)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.fetchWeightedElements(PSIPresentationBgRendererWrapper.java:66)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:184)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:206)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-28 09:42:08,767 [326015130] SEVERE - #c.i.o.a.i.ApplicationImpl - IntelliJ IDEA 2023.2.1  Build #IC-232.9559.62
2023-08-28 09:42:08,767 [326015130] SEVERE - #c.i.o.a.i.ApplicationImpl - JDK: 17.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-08-28 09:42:08,767 [326015130] SEVERE - #c.i.o.a.i.ApplicationImpl - OS: Windows 11
2023-08-28 09:42:11,235 [326017598]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlang' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:18,074 [326024437]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlan' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:18,217 [326024580]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlan' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:19,848 [326026211]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:20,005 [326026368]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:25,552 [326031915]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erl' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:25,680 [326032043]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:25,855 [326032218]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlag' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:26,870 [326033233]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:27,042 [326033405]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:28,002 [326034365]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:28,257 [326034620]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erl' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:28,542 [326034905]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'er' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:28,781 [326035144]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'e' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:29,550 [326035913]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erl' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:29,724 [326036087]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erla' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:29,866 [326036229]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlan' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:30,071 [326036434]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlang' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
2023-08-28 09:42:32,955 [326039318]   WARN - #c.i.i.a.s.WaitForContributorsListenerWrapper - Contributor 'FileSearchEverywhereContributor' did not finish search for 'erlang' in 3000ms. Maybe it should implement PossibleSlowContributor interface?
```

**Comment by zyuyou** [comment]
it's idea's bug
