### ISSUE TITLE
JpsErlangModelSerializerExtension: JVMCFRE199E bad major version 61.0

### ISSUE THREAD

**Issue by sahkaa** [ignatov/intellij-erlang#1022]
Hello
My project is
https://github.com/sahkaa/erlang-test
My versions:
IntelliJ IDEA 2023.2.2 
Build #IU-232.9921.47, built on September 12, 2023
Runtime version: 17.0.8+7-b1000.22 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2

Non-Bundled Plugins:
    org.jetbrains.erlang (0.11.1205)
    Dart (232.9559.10)
    com.haulmont.jpab (2023.3.5-232)
    io.flutter (75.1.4)

Kotlin: 232-1.9.0-IJ9921.47

Erlang Plugin version: 0.11.1205

![image](https://github.com/ignatov/intellij-erlang/assets/22525075/c1035158-b253-4ea7-a3f8-33e37b675583)

Facing that issue:
```
Internal error (java.lang.UnsupportedClassVersionError): JVMCFRE199E bad major version 61.0 of class=org/intellij/erlang/jps/model/JpsErlangModelSerializerExtension, the maximum supported major version is 55.0; offset=6
java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 61.0 of class=org/intellij/erlang/jps/model/JpsErlangModelSerializerExtension, the maximum supported major version is 55.0; offset=6
	at java.base/java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.base/java.lang.ClassLoader.defineClassInternal(ClassLoader.java:467)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:428)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:688)
	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1093)
	at java.base/java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1078)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:782)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:603)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1177)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1092)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1075)
	at java.base/java.lang.Class.forNameImpl(Native Method)
	at java.base/java.lang.Class.forName(Class.java:418)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1224)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1235)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1284)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1319)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1404)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:149)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:113)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:105)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:58)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:47)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.getSdkPropertiesSerializer(JpsSdkTableSerializer.java:132)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdk(JpsSdkTableSerializer.java:67)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdks(JpsSdkTableSerializer.java:59)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:117)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:110)
	at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:45)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:73)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:63)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalSettings(JpsGlobalLoader.java:45)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:20)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:35)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:68)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:363)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:212)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)

```

**Comment by yangyuanqiang** [comment]
Same error.
IntelliJ IDEA 2023.3.4
Erlang version 26.2.2

**Comment by salespaulo** [comment]
Same error.
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
