### ISSUE TITLE
Debugging failed with: Failed to setup debugger environment using Intelij 2023.2.5, OSX 13.5.2 (22G91)

### ISSUE THREAD

**Issue by obi458** [ignatov/intellij-erlang#1024]
IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
Runtime version: 17.0.9+7-b1000.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 24576M
Cores: 16
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9559.64)
    com.intellij.ideolog (203.0.30.0)
    org.jetbrains.plugins.go (232.9559.65)
    org.jetbrains.erlang (0.11.1205)
    mobi.hsz.idea.gitignore (4.5.1)
    com.intellij.plugins.html.instantEditing (232.8660.142)

Kotlin: 232-1.9.0-IJ10227.8

in 

private static void copyBeamTo(String beamName, File directory) throws IOException {.....

**Comment by aberfeldy** [comment]
same behaviour with my intellij + erlang.
logs show:
```
2023-12-11 14:25:06,574 [20241083]   INFO - #c.i.e.r.ExecutionUtil - Error running 'sqrs.doit':<br>Failed to setup debugger environment
com.intellij.execution.ExecutionException: Failed to setup debugger environment
	at org.intellij.erlang.debugger.xdebug.ErlangXDebugProcess.setUpErlangDebuggerCodePath(ErlangXDebugProcess.java:392)
	at org.intellij.erlang.debugger.xdebug.ErlangXDebugProcess.runDebugTarget(ErlangXDebugProcess.java:338)
	at org.intellij.erlang.debugger.xdebug.ErlangXDebugProcess.<init>(ErlangXDebugProcess.java:109)
	at org.intellij.erlang.debugger.xdebug.ErlangDebugRunner$1.start(ErlangDebugRunner.java:48)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:274)
	at com.intellij.xdebugger.impl.XDebuggerManagerImpl.startSession(XDebuggerManagerImpl.java:219)
	at org.intellij.erlang.debugger.xdebug.ErlangDebugRunner.doExecute(ErlangDebugRunner.java:44)
	at com.intellij.execution.runners.GenericProgramRunner$execute$1.invoke(GenericProgramRunner.kt:20)
	at com.intellij.execution.runners.GenericProgramRunner$execute$1.invoke(GenericProgramRunner.kt:19)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:207)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:205)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda$2(ExecutionManagerImpl.kt:269)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.io.IOException: Failed to locate debugger module: debugnode.beam
	at org.intellij.erlang.debugger.xdebug.ErlangXDebugProcess.copyBeamTo(ErlangXDebugProcess.java:399)
	at org.intellij.erlang.debugger.xdebug.ErlangXDebugProcess.setUpErlangDebuggerCodePath(ErlangXDebugProcess.java:386)
	... 49 more
```

**Comment by obi458** [comment]
Same on 2023.3.2 using 0.11.1216 on OSX 13.5.2

**Comment by obi458** [comment]
Any timeline to fix?

**Comment by ignatov** [comment]
Hi! Could you please provide a sample project that I can use to reproduce the bug?

**Comment by obi458** [comment]
1) Run -> works
2) Debug -> failed
[debugtest.zip](https://github.com/ignatov/intellij-erlang/files/14485568/debugtest.zip)

**Comment by halotukozak** [comment]
+1

**Comment by dong50252409** [comment]
+1 
I hope to fix this bug soon
