### ISSUE TITLE
我正在使用WebStorm 2024.3.1，定义.hrl目录会导致此问题。Erlang插件版本为1243。

### ISSUE THREAD

**Issue by imLaoYang** [ignatov/intellij-erlang#1056]
![image](https://github.com/user-attachments/assets/7331d540-0e14-4eff-9428-708dfdffcf02)

**Comment by imLaoYang** [comment]
Exceptions occurred on invoking the intention 'Find include' (class org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix) on a copy of the file.

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#137,DefaultDispatcher-worker-50,5,main] 1299380684 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#57,AWT-EventQueue-0,6,main] 503310675
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:218)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:209)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:78)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:274)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:309)
	at com.intellij.ui.popup.list.ListPopupImpl.<init>(ListPopupImpl.java:82)
	at com.intellij.ui.popup.PopupFactoryImpl.createListPopup(PopupFactoryImpl.java:447)
	at com.jetbrains.rdserver.ui.popup.BackendBePopupFactory.createListPopup(BackendBePopupFactory.kt:249)
	at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix.displayPopupListDialog(ErlangFindIncludeQuickFix.java:119)
	at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix.applyFix(ErlangFindIncludeQuickFix.java:91)
	at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix.applyFix(ErlangFindIncludeQuickFix.java:51)
	at com.intellij.codeInspection.LocalQuickFix.generatePreview(LocalQuickFix.java:81)
	at com.intellij.codeInspection.ex.QuickFixWrapper.generatePreview(QuickFixWrapper.java:234)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.generatePreview(IntentionActionWithTextCaching.java:259)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$3$lambda$2$lambda$1(IntentionPreviewComputable.kt:121)
	at com.intellij.model.SideEffectGuard$Companion.computeWithAllowedSideEffectsBlocking(SideEffectGuard.kt:42)
	at com.intellij.model.SideEffectGuard$Companion.computeWithoutSideEffects(SideEffectGuard.kt:27)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$3$lambda$2(IntentionPreviewComputable.kt:120)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.lambda$postponeFormattingInside$2(PostprocessReformattingAspectImpl.java:137)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:146)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:136)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$3(IntentionPreviewComputable.kt:119)
	at com.intellij.codeInsight.intention.preview.IntentionPreviewUtils.previewSession(IntentionPreviewUtils.java:127)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview(IntentionPreviewComputable.kt:118)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.generatePreview(IntentionPreviewComputable.kt:87)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent(IntentionPreviewComputable.kt:63)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:46)
	at com.intellij.codeInsight.intention.impl.IntentionHintComponent$IntentionPopup.lambda$getPreviewHandler$4(IntentionHintComponent.java:858)
	at com.intellij.codeInsight.intention.impl.preview.PreviewHandler.lambda$new$0(PreviewHandler.java:53)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewPopupUpdateProcessor$updatePopup$4.invokeSuspend$lambda$0(IntentionPreviewPopupUpdateProcessor.kt:126)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewPopupUpdateProcessor$updatePopup$4.invokeSuspend(IntentionPreviewPopupUpdateProcessor.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

**Comment by deadshot465** [comment]
Seems related to #1055 . I'm having the same problem when trying to open an existing Rebar3 project.
