### ISSUE TITLE
Development on Windows

### ISSUE THREAD

**Issue by Enouk** [ignatov/intellij-erlang#172]
Hi.

I have tried to run the unit test on windows but it fails with the following error, do you know what is need to get this working?

ERROR: Failed to load native filesystem for Windows
java.io.FileNotFoundException: Native filesystem .dll is missing, home: C:\Users\nilmar2.IdeaIC12\system\plugins-sandbox\test
    at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:50)
    at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:71)
    at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:64)
    at com.intellij.openapi.util.io.FileUtil.delete(FileUtil.java:417)
    at com.intellij.testFramework.UsefulTestCase.tearDown(UsefulTestCase.java:132)
    at com.intellij.testFramework.PlatformLiteFixture.tearDown(PlatformLiteFixture.java:74)
    at com.intellij.testFramework.ParsingTestCase.tearDown(ParsingTestCase.java:170)
    at junit.framework.TestCase.runBare(TestCase.java:140)
    at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:276)
    at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:288)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.AssertionError: Failed to load native filesystem for Windows
    at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:55)
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:65)
    at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:59)
    at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:71)
    at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:64)
    at com.intellij.openapi.util.io.FileUtil.delete(FileUtil.java:417)
    at com.intellij.testFramework.UsefulTestCase.tearDown(UsefulTestCase.java:132)
    at com.intellij.testFramework.PlatformLiteFixture.tearDown(PlatformLiteFixture.java:74)
    at com.intellij.testFramework.ParsingTestCase.tearDown(ParsingTestCase.java:170)
    at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:276)
    at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:288)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

java.lang.NoClassDefFoundError: Could not initialize class com.intellij.openapi.util.io.FileSystemUtil
    at com.intellij.openapi.util.io.FileUtil.delete(FileUtil.java:417)
    at com.intellij.testFramework.UsefulTestCase.tearDown(UsefulTestCase.java:132)
    at com.intellij.testFramework.PlatformLiteFixture.tearDown(PlatformLiteFixture.java:74)
    at com.intellij.testFramework.ParsingTestCase.tearDown(ParsingTestCase.java:170)
    at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:276)
    at com.intellij.testFramework.UsefulTestCase$3.run(UsefulTestCase.java:288)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:641)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:611)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Process finished with exit code -1

**Comment by sharwell** [comment]
@Enouk We saw a similar issue to this today. Did you happen to find a resolution for it that could help us? Thanks! :smile:

**Comment by sharwell** [comment]
We found a solution - the following is from a dev on my team:

> Take a look at http://www.theusenetarchive.com/usenet-message-not-able-to-load-ideawin32-dll-14341891.htm. Copying the **IdeaWin32.dll** from the **IDEA_HOME/bin** to **USER_HOME/.IdeaIC12/system/plugins-sandbox/test/bin** worked.

**Comment by vahididoo** [comment]
I had the same issue. In the intellij SDK development guide, it says to set the unit test parameters to this:
-ea -Xbootclasspath/p:../out/classes/production/boot -XX:+HeapDumpOnOutOfMemoryError -Xmx512m -XX:MaxPermSize=320m -Didea.system.path=../test-system -Didea.home.path=../ -Didea.config.path=../test-config -Didea.test.group=ALL_EXCLUDE_DEFINED

where as the right parameter for `-Didea.home.path ` is the absolute path to your SDK's source folder. In my case it is:
-Didea.home.path=E:/Workspace/IdeaSDKs/ideaIU-12.1.7b
