### ISSUE TITLE
Erlang Compiler config page doesn't show up

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#596]
IDEA 14.1.1, Erlang 67dee4d

Erlang Compiler config page does now show up, not sure when it broke but it definitely worked with a stable build.

![screen shot 2015-04-21 at 2 56 21 pm](https://cloud.githubusercontent.com/assets/1018740/7263492/e068b72c-e836-11e4-990b-0502e95749b3.png)

**Comment by deadok22** [comment]
I can't reproduce it. 

Is there anything relevant in logs? Does it use CPU excessively when you try to open the tab?

**Comment by istocniks** [comment]
It turns out that logs do have something!
```
 Marker - Apr 30, 2015, 10:34:10 AM
2015-04-30 10:34:14,235 [ 326658]  ERROR - openapi.options.ConfigurableEP - null 
java.lang.NullPointerException
	at org.intellij.erlang.settings.ErlangExternalToolsConfigurable.<init>(ErlangExternalToolsConfigurable.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:241)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:167)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.wrapConfigurable(ConfigurableWrapper.java:49)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.buildConfigurablesList(ConfigurableExtensionPointUtil.java:54)
	at com.intellij.openapi.options.ex.ConfigurablesGroupBase.getConfigurables(ConfigurablesGroupBase.java:49)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:98)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:83)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:99)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:90)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:88)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:253)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:244)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-04-30 10:34:14,236 [ 326659]  ERROR - openapi.options.ConfigurableEP - IntelliJ IDEA 14.1.2  Build #IU-141.713.2 
2015-04-30 10:34:14,236 [ 326659]  ERROR - openapi.options.ConfigurableEP - JDK: 1.6.0_65 
2015-04-30 10:34:14,237 [ 326660]  ERROR - openapi.options.ConfigurableEP - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-30 10:34:14,237 [ 326660]  ERROR - openapi.options.ConfigurableEP - Vendor: Apple Inc. 
2015-04-30 10:34:14,237 [ 326660]  ERROR - openapi.options.ConfigurableEP - OS: Mac OS X 
```

**Comment by ignatov** [comment]
If you're building the project from the source code, please enable the 'UI Designer' plugin. I believe that should fix another issue with extract method dialog.

**Comment by istocniks** [comment]
Not really sure why do I need to install a plugin here... The extract method functionality worked for me before without it.

**Comment by istocniks** [comment]
Oh, you mean it is needed to properly build the Erlang plugin project?

**Comment by istocniks** [comment]
Installed UI Designer, re-built Erlang, didn't help

**Comment by deadok22** [comment]
Sorry for a late answer. Yes, it's needed to build the Erlang plugin project, as we use the UI Designer plugin to build some of UI components. Have you tried running "Build" -> "Rebuild Project"?

**Comment by istocniks** [comment]
Wow, I tried again and it worked, don't know why didn't it help on the first time. Thank you! It's probably worth to mention UI Designer in CONTRIBUTING.md

**Comment by ignatov** [comment]
Thanks, done.
