### ISSUE TITLE
Can't select Erlang_SDK

### ISSUE THREAD

**Issue by JeremyOuyang** [ignatov/intellij-erlang#599]
Why can't i select my Erlang path when i select home directory for Erlang_SDK? I'm sure my path is correct. When i press the ''ok'' button , it has not any response. My os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
Why can't I select my Erlang path when I select home directory for Erlang_SDK? I'm sure my path is correct. When I press the ''ok'' button , it has not any response. My os is win 7 X 64.

**Comment by JeremyOuyang** [comment]
Why can't I select my Erlang path when I select home directory for Erlang_SDK? I'm sure my path is correct. When I press the ''ok'' button , it has not any response. My os is win 7 X 64.

**Comment by deadok22** [comment]
Hi @JeremyOuyang! Please repeat your actions once again and share your log files right after you did it.

https://intellij-support.jetbrains.com/entries/23352446-Locating-IDE-log-files

**Comment by JeremyOuyang** [comment]
Hi @deadok22 ! Now I will show you my log files:
      2015-05-13 10:26:08,590 [ 238017]  ERROR - llij.ide.plugins.PluginManager - org/intellij/erlang/jps/model/JpsErlangSdkType 
java.lang.NoClassDefFoundError: org/intellij/erlang/jps/model/JpsErlangSdkType
	at org.intellij.erlang.sdk.ErlangSdkType.getTopLevelExecutable(ErlangSdkType.java:131)
	at org.intellij.erlang.sdk.ErlangSdkType.isValidSdkHome(ErlangSdkType.java:124)
	at com.intellij.openapi.projectRoots.SdkType$1.validateSelectedFiles(SdkType.java:157)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.doOKAction(FileChooserDialogImpl.java:409)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1821)
	at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1787)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)

**Comment by deadok22** [comment]
@JeremyOuyang, it looks like your plugin installation is corrupted.

Try re-installing it and make sure you use whole ```Erlang.zip``` this time, not individual files from it.

**Comment by JeremyOuyang** [comment]
Thank you very much @deadok22 ! The problem had been solved, when I installed it from  browse repositories. Before, I installed it from disk, and the "lib" folder consist of jps/jps-plugin.jar,  erlang.jar, jps-shared.jar, OtpErlang.jar. So how can i install it from disk?

**Comment by ignatov** [comment]
You need to download the entire zip file, not a several jars, please see [Apple discussion forum](https://discussions.apple.com/thread/1483114).
