### ISSUE TITLE
Clicking on "Configure rebar" throws exception

### ISSUE THREAD

**Issue by istocniks** [ignatov/intellij-erlang#612]
Intellij IDEA 14.1.3, intellij-erlang 80c61b6

![screen shot 2015-06-02 at 12 15 13 pm](https://cloud.githubusercontent.com/assets/1018740/7944724/4daf876a-0921-11e5-9b60-f6acebd13a0f.png)

The exception is:
```
java.lang.AssertionError
	at org.intellij.erlang.configuration.ErlangCompilerOptionsConfigurable$1.actionPerformed(ErlangCompilerOptionsConfigurable.java:57)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
	...
```
am I building the plugin without any required dependencies again?

**Comment by deadok22** [comment]
It's definitely a bug and it's reproducible on my machine.
