### ISSUE TITLE
Importing from rebar is broken, doesn't detect rebar version

### ISSUE THREAD

**Issue by magicgoose** [ignatov/intellij-erlang#698]
When trying to import a rebar project,
whatever I put into `Rebar/Path` (tried both globally installed rebar 2.6.1 and also the one downloaded through IDEA), the `Rebar/Version` is `N/A` and the button `Next` is inactive/not clickable.

This makes it impossible to import a rebar project.

**Comment by deadok22** [comment]
What's your OS?

**Comment by magicgoose** [comment]
OS X 10.11.1
Tried both IntelliJ IDEA 14 and 15

**Comment by deadok22** [comment]
Please, do the following:
1. Open "Tools" -> "IDE Scripting Console"
2. Choose "Groovy" as your scripting language
3. Paste the script below in the editor
4. Select the pasted script in your editor, and hit "Ctrl+Enter" or "Cmd+Enter" - I'm not sure which one works on Mac
5. Share the script's output
```groovy
import com.intellij.ide.plugins.PluginManager;
import com.intellij.openapi.extensions.PluginId;

plugin = PluginManager.getPlugin(PluginId.findId("org.jetbrains.erlang"))
cl = plugin.getPluginClassLoader()

sdk = cl.loadClass("org.intellij.erlang.jps.model.JpsErlangSdkType")
epu = cl.loadClass("org.intellij.erlang.utils.ExtProcessUtil")

escript = sdk.getExecutableFileName(sdk.SCRIPT_INTERPRETER);
rebar = "YOUR_REBAR_PATH"

IDE.print("File exists: " + new File(rebar).exists())

output = epu.execAndGetFirstLine(3000, escript, rebar, "--version");

IDE.print("OUT: " + output.getStdOut())
IDE.print("ERR: " + output.getStdErr())
```

**Comment by magicgoose** [comment]
Is it necessary to open a project to do this? I cannot see a way without it…

**Comment by deadok22** [comment]
Yes, you need a project to open IDE Scripting Console.

**Comment by magicgoose** [comment]
Replaced `YOUR_REBAR_PATH` with what I used — `/usr/local/bin/rebar`
Output:
```
File exists: true
OUT: 
ERR: 
```

**Comment by deadok22** [comment]
Well, this is weird, to say the least. 

Try executing the same thing manually:
```
escript /usr/local/bin/rebar --version
```

**Comment by magicgoose** [comment]
```
$ escript /usr/local/bin/rebar --version
rebar 2.6.1 18 20151014_015616 No VCS info available.
```

**Comment by deadok22** [comment]
Looks like we're suppressing some errors which are to be handled instead.

Try running:
```groovy
import com.intellij.execution.configurations.GeneralCommandLine;

new GeneralCommandLine("escript", "/home/user/projects/rebar/rebar", "--version").createProcess().waitFor()
```

**Comment by magicgoose** [comment]
```
IOException: error=2, No such file or directory
```

**Comment by deadok22** [comment]
Could you share a stack trace as well? It could be, 'escript' is not on your PATH, but I can't be sure.

**Comment by magicgoose** [comment]
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "escript": error=2, No such file or directory
		at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:296)
		at com.intellij.execution.configurations.GeneralCommandLine$createProcess.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
		at Script8.run(Script8.groovy:5)
		at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:345)
		at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:145)
		at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
		at com.intellij.execution.console.RunIdeConsoleAction.executeQuery(RunIdeConsoleAction.java:204)
		at com.intellij.execution.console.RunIdeConsoleAction.access$200(RunIdeConsoleAction.java:70)
		at com.intellij.execution.console.RunIdeConsoleAction$MyRunAction.actionPerformed(RunIdeConsoleAction.java:298)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:593)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:644)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:483)
		at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	Caused by: java.io.IOException: Cannot run program "escript": error=2, No such file or directory
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
		at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:306)
		at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:292)
		... 23 more
	Caused by: java.io.IOException: error=2, No such file or directory
		at java.lang.UNIXProcess.forkAndExec(Native Method)
		at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
		at java.lang.ProcessImpl.start(ProcessImpl.java:134)
		at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
		... 25 more


(Produced by script:)

    import com.intellij.execution.configurations.GeneralCommandLine;
    
    try {
        new GeneralCommandLine("escript", "/Users/MY_USER/…/…/PROJECT_DIR/", "--version").createProcess().waitFor()
    } catch (ex) {
        IDE.print(ex)
    
        sw = new StringWriter();
        pw = new PrintWriter(sw);
        ex.printStackTrace(pw);
        IDE.print(sw.toString()); // stack trace as a string
    }

**Comment by deadok22** [comment]
Looks like escript is not on your PATH, indeed.

Check your PATH variable with the following script:
```groovy
IDE.print(System.getenv("PATH"))
```

Compare the output with ```echo $PATH``` command in your terminal. If it's the case, you need to do something like this: http://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications to make it work.

In any case, I'll make these error messages appear, so that we don't have to do this scripting next time.

**Comment by magicgoose** [comment]
```
> IDE.print(System.getenv("PATH"))
/usr/bin:/bin:/usr/sbin:/sbin
```
quite lonely here…

```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/•••/Library/Android/sdk/platform-tools
```

**Comment by magicgoose** [comment]
Is it supposed to work out of the box, or all users must do some manual tricks with environment variables?

**Comment by magicgoose** [comment]
I'm currently using a script which sets environment variables using launchctl,
it has this line, for example:
`launchctl setenv PATH "$PATH:/Users/•••/Library/Android/sdk/platform-tools"`

but it clearly does not have effect in IDEA, although this method is one of the suggested methods in the answer you linked (https://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications)

**Comment by casidiablo** [comment]
@magicgoose it also didn't work for me. What I did for now is this:

```
cd /usr/bin
sudo ln -sv /usr/local/bin/escript
```

**Comment by arpunk** [comment]
@casidiablo This might get in your way if you get to run multiple Erlang installations. (Oh hai!)

**Comment by casidiablo** [comment]
Hey arpunk! It's been a long time!

I will try to fix it the proper way then.

**Comment by deadok22** [comment]
I don't have a Mac, so I'd be glad if you figured out what the solution is. Once we have it, we can add it to the repository description, so that users can find it right away.

**Comment by sergium** [comment]
IMHO problem with "escript" location (IDEA ignoring the PATH env?)

```
sv@sv-air $ echo $PATH
/Users/sv/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/sv/bi
you can 'fix' it starting IDEA with script and 
```

---- start as  .app from Finder | Dock | Spotlight  -> lost $PATH 
```
> IDE.print(System.getenv("PATH"))
/usr/bin:/bin:/usr/sbin:/sbin
```

---- start from console -> keep $PATH
```
sv@sv-air $ open -a "IntelliJ IDEA 15 CE"

> IDE.print(System.getenv("PATH"))
/usr/local/bin:/Users/sv/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/sv/bin
```

@deadok22 - "escript" located inside the OTP-dir, could this bug related to the selection of OTP-version for the project (multiple OTP versions on machine available -> select one and lost 'OS' environment?)

**Comment by deadok22** [comment]
Hi @sergium,

OTP version selected for the project has nothing to do with the bug. As you may have seen in the script above, we simply call ```escript``` without specifying it's path. So ```escript``` should be on IntelliJ's PATH.

And the issue is, environment variables for applications run from console differ from applications run via Finder. It would be great if you figured out how to alter PATH for Finder-launched apps and shared it.

Cheers!

**Comment by sergium** [comment]
Hi @deadok22,

Ok I would check.

btw - why you can't call "escript" via the full-path to the current project's OTP (it's part of OTP anyway - so, IMHO it could lead to funny things: OTP X used to start "erl",  but "escript" from OTP Y used to start rebar - only because it was default in the env?)

**Comment by deadok22** [comment]
Well, in some cases we can call escript directly, but there are cases where there's no project opened, and we need to check rebar version.

Also, AFAIK, one cannot simply run any program via it's full path =) Try running something that's not on IDEA's PATH from your IDE Scripting Console.

**Comment by ginnun** [comment]
A simple work around is starting IDE from your terminal.
run this at your terminal: `open Applications/IntelliJ\ IDEA.app`
