### ISSUE TITLE
Beam File not being created

### ISSUE THREAD

**Issue by wmorrison1967** [ignatov/intellij-erlang#708]
Hello,
        I am using intellj 15.0 build IU-143,381 with erlang plugin 0.6.837 and SDK 18 (erts7.1).  The issue is that no beam file is being created in the out/production/servername directory when the project is built.  

Regards,
Will

**Comment by deadok22** [comment]
Please, attach logs (Help -> Show logs in ...) and share more details on your project setup - specifically, on how your IntelliJ modules are setup, what are their dependencies.

Does 'Rebuild Project' help?

**Comment by wmorrison1967** [comment]
Thank deadok22, rebuild project did nothing.  Having issue upload a zip file of the build and idea logs so I have place snippets here of both files
.
This is the Idea log:
2016-01-06 22:28:13,406 [6542573]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 15.0  Build #IU-143.381.42 
2016-01-06 22:28:13,407 [6542574]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_51 
2016-01-06 22:28:13,407 [6542574]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) Server VM 
2016-01-06 22:28:13,407 [6542574]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2016-01-06 22:28:13,407 [6542574]  ERROR - aemon.impl.PassExecutorService - OS: Windows 8 
2016-01-06 22:28:13,407 [6542574]  ERROR - aemon.impl.PassExecutorService - Last Action: EditorBackSpace 
2016-01-06 22:29:08,202 [6597369]   INFO - openapi.editor.impl.EditorImpl - Cache hits:16384, total requests:22017,file://C:/devxmpp/Erlang Projects/src/factorial_server.erl 
2016-01-06 22:37:47,149 [7116316]   INFO - openapi.editor.impl.EditorImpl - Cache hits:20480, total requests:27126,file://C:/devxmpp/Erlang Projects/src/factorial_server.erl 
2016-01-06 22:42:16,927 [7386094]   INFO - ij.compiler.impl.CompileDriver - COMPILATION STARTED (BUILD PROCESS) 
2016-01-06 22:42:17,003 [7386170]   INFO - PrepareDependenciesCompileTask - Prepare build order for project gen_server 
2016-01-06 22:42:18,514 [7387681]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar 
2016-01-06 22:42:20,556 [7389723]   INFO - .GenericCompilerPersistentData - Compiler info file doesn't exists: C:\Users\admin\.IntelliJIdea15\system\compiler\erlang projects.472d9bc8\.caches\jasper_validator\info 
2016-01-06 22:42:20,556 [7389723]   INFO - ler.impl.GenericCompilerRunner - Clearing cache for Jasper Validator 
2016-01-06 22:42:20,630 [7389797]   INFO - s.impl.ProjectManagerComponent - project roots have changed 
2016-01-06 22:42:20,681 [7389848]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 0ms; general responsiveness: ok; EDT responsiveness: ok 
2016-01-06 22:42:20,681 [7389848]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED (BUILD PROCESS); Errors: 0; warnings: 0 took 3669 ms: 0 min 3sec 
2016-01-06 22:42:20,685 [7389852]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 4ms; general responsiveness: ok; EDT responsiveness: ok 
2016-01-06 22:42:20,972 [7390139]   INFO - j.compiler.server.BuildManager - BUILDER_PROCESS [stdout]: Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar 
2016-01-06 22:44:31,981 [7521148]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
2016-01-06 22:44:32,040 [7521207]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 79 ms 
2016-01-06 22:46:27,101 [7636268]  ERROR - ellij.openapi.ui.DialogBuilder - Assertion failed: Dialog title shouldn't be empty or null: [] 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:144)
	at com.intellij.openapi.ui.DialogBuilder.showImpl(DialogBuilder.java:86)
	at com.intellij.openapi.ui.DialogBuilder.show(DialogBuilder.java:56)
	at com.intellij.openapi.ui.Messages.showTextAreaDialog(Messages.java:1235)
	at com.intellij.ui.RawCommandLineEditor$1.actionPerformed(RawCommandLineEditor.java:57)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1637)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1586)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1601)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$9.perform(ChooseRunConfigurationPopup.java:949)
	at com.intellij.execution.actions.ChooseRunConfigurationPopup$ConfigurationListPopupStep$2.run(ChooseRunConfigurationPopup.java:516)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


This is the build log:

2016-01-06 22:42:18,514 [      0]   INFO - etbrains.jps.cmdline.BuildMain - Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar
2016-01-06 22:42:18,884 [    370]   INFO - etbrains.jps.cmdline.BuildMain - Connection to IDE established in 343 ms
2016-01-06 22:42:19,045 [    531]   INFO - jps.cmdline.JpsModelLoaderImpl - Loading model: project path = C:/devxmpp/Erlang Projects, global options path = C:/Users/admin/.IntelliJIdea15/config/options
2016-01-06 22:42:19,621 [   1107]   INFO - jps.cmdline.JpsModelLoaderImpl - Model loaded in 576 ms
2016-01-06 22:42:19,622 [   1108]   INFO - jps.cmdline.JpsModelLoaderImpl - Project has 1 modules, 0 libraries
2016-01-06 22:42:19,780 [   1266]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=688586752
2016-01-06 22:42:20,080 [   1566]   INFO - .incremental.IncProjectBuilder - Building project; isRebuild:true; isMake:false parallel compilation:false
2016-01-06 22:42:20,084 [   1570]   INFO - kotlin.jps.build.KotlinBuilder - is Kotlin incremental compilation enabled: true
2016-01-06 22:42:20,084 [   1570]   INFO - kotlin.jps.build.KotlinBuilder - Label in local history: build started eaad3f20
2016-01-06 22:42:20,115 [   1601]   INFO - r.api.ClassFilesIndicesBuilder - class files data index disabled
2016-01-06 22:42:20,325 [   1811]   INFO - lang.jps.builder.ErlangBuilder - Computing dirty files
2016-01-06 22:42:20,335 [   1821]   WARN - lang.jps.builder.ErlangBuilder - Unexpected dirty file detected. Please, report to https://github.com/ignatov/intellij-erlang/issues/685. Path: C:\devxmpp\Erlang Projects\src\factorial_server.erl
2016-01-06 22:42:20,335 [   1821]   WARN - lang.jps.builder.ErlangBuilder - Unexpected dirty file detected. Please, report to https://github.com/ignatov/intellij-erlang/issues/685. Path: C:\devxmpp\Erlang Projects\src\factorial_client.erl
2016-01-06 22:42:20,335 [   1821]   WARN - lang.jps.builder.ErlangBuilder - Unexpected dirty file detected. Please, report to https://github.com/ignatov/intellij-erlang/issues/685. Path: C:\devxmpp\Erlang Projects\src\factorial_logic.erl
2016-01-06 22:42:20,344 [   1830]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational
2016-01-06 22:42:20,356 [   1842]   INFO - lang.jps.builder.ErlangBuilder - Build module Erlang 'gen_server'
2016-01-06 22:42:20,358 [   1844]   INFO - lang.jps.builder.ErlangBuilder - Sources is up to date for module "gen_server".
2016-01-06 22:42:20,359 [   1845]   INFO - lang.jps.builder.ErlangBuilder - Test sources is up to date for module "gen_server".
2016-01-06 22:42:20,973 [      0]   INFO - etbrains.jps.cmdline.BuildMain - Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar
2016-01-06 22:42:21,305 [    332]   INFO - etbrains.jps.cmdline.BuildMain - Connection to IDE established in 303 ms
2016-01-06 22:42:21,315 [    342]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational
2016-01-06 22:42:21,336 [    363]   INFO - jps.cmdline.JpsModelLoaderImpl - Loading model: project path = C:/devxmpp/Erlang Projects, global options path = C:/Users/admin/.IntelliJIdea15/config/options
2016-01-06 22:42:21,698 [    725]   INFO - jps.cmdline.JpsModelLoaderImpl - Model loaded in 362 ms
2016-01-06 22:42:21,698 [    725]   INFO - jps.cmdline.JpsModelLoaderImpl - Project has 1 modules, 0 libraries
2016-01-06 22:42:21,804 [    831]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=688586752
2016-01-06 22:42:22,047 [   1074]   INFO - etbrains.jps.cmdline.BuildMain - Pre-loaded process ready in 1075 ms
2016-01-06 22:42:22,099 [   1126]   INFO - etbrains.jps.cmdline.BuildMain - Build canceled, but no build session is running. Exiting.
2016-01-06 22:48:15,095 [      0]   INFO - etbrains.jps.cmdline.BuildMain - Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar
2016-01-06 22:48:15,416 [    321]   INFO - etbrains.jps.cmdline.BuildMain - Connection to IDE established in 294 ms
2016-01-06 22:48:15,508 [    413]   INFO - jps.cmdline.JpsModelLoaderImpl - Loading model: project path = C:/devxmpp/Erlang Projects, global options path = C:/Users/admin/.IntelliJIdea15/config/options
2016-01-06 22:48:15,911 [    816]   INFO - jps.cmdline.JpsModelLoaderImpl - Model loaded in 403 ms
2016-01-06 22:48:15,911 [    816]   INFO - jps.cmdline.JpsModelLoaderImpl - Project has 1 modules, 0 libraries
2016-01-06 22:48:16,027 [    932]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=688586752
2016-01-06 22:48:16,258 [   1163]   INFO - .incremental.IncProjectBuilder - Building project; isRebuild:false; isMake:true parallel compilation:false
2016-01-06 22:48:16,261 [   1166]   INFO - kotlin.jps.build.KotlinBuilder - is Kotlin incremental compilation enabled: true
2016-01-06 22:48:16,261 [   1166]   INFO - kotlin.jps.build.KotlinBuilder - Label in local history: build started 182b48c8
2016-01-06 22:48:16,271 [   1176]   INFO - r.api.ClassFilesIndicesBuilder - class files data index disabled
2016-01-06 22:48:16,313 [   1218]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational
2016-01-06 22:48:16,343 [   1248]   INFO - lang.jps.builder.ErlangBuilder - Computing dirty files
2016-01-06 22:48:16,375 [   1280]   INFO - lang.jps.builder.ErlangBuilder - Build module Erlang 'gen_server'
2016-01-06 22:48:16,375 [   1280]   INFO - lang.jps.builder.ErlangBuilder - Sources is up to date for module "gen_server".
2016-01-06 22:48:16,375 [   1280]   INFO - lang.jps.builder.ErlangBuilder - Test sources is up to date for module "gen_server".
2016-01-06 22:48:16,900 [      0]   INFO - etbrains.jps.cmdline.BuildMain - Build process started. Classpath: /C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/jps-launcher.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/jre/lib/tools.jar;/C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/optimizedFileManager.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 15.0/lib/ecj-4.4.jar
2016-01-06 22:48:17,212 [    312]   INFO - etbrains.jps.cmdline.BuildMain - Connection to IDE established in 284 ms
2016-01-06 22:48:17,222 [    322]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational
2016-01-06 22:48:17,243 [    343]   INFO - jps.cmdline.JpsModelLoaderImpl - Loading model: project path = C:/devxmpp/Erlang Projects, global options path = C:/Users/admin/.IntelliJIdea15/config/options
2016-01-06 22:48:17,614 [    714]   INFO - jps.cmdline.JpsModelLoaderImpl - Model loaded in 371 ms
2016-01-06 22:48:17,614 [    714]   INFO - jps.cmdline.JpsModelLoaderImpl - Project has 1 modules, 0 libraries
2016-01-06 22:48:17,718 [    818]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=200; buffer=10; max=688586752
2016-01-06 22:48:17,890 [    990]   INFO - etbrains.jps.cmdline.BuildMain - Pre-loaded process ready in 991 ms

**Comment by deadok22** [comment]
Please, archive your whole project and send it to - deadok22 [at] gmail.com, if possible. If not, - describe your project layout as I asked in my previous comment.

As you can see from the log, it's an issue we can't figure out for a long time:
```
2016-01-06 22:42:20,335 [ 1821] WARN - lang.jps.builder.ErlangBuilder - Unexpected dirty file detected. Please, report to #685. Path: C:\devxmpp\Erlang Projects\src\factorial_logic.erl
```

**Comment by wmorrison1967** [comment]
I archive the entire project check your email.

**Comment by deadok22** [comment]
Thank you for sharing your project with me @wmorrison1967.

This issue has been fixed recently (see #695), but the fix hasn't make it to a release yet. 

Use the latest build from here: https://teamcity.jetbrains.com/viewType.html?buildTypeId=IntellijIdeaPlugins_IntellijErlang_Tests

Cheers!

**Comment by wmorrison1967** [comment]
Hi Sergey,
       I am not sure what to do at the TC website.  I am using windows, so
a windows 7,8,10 agent I am thinking is what I would need.  Also connecting
as quest I am not seeing how to download the pluggin.

Regards,
Will

**Comment by deadok22** [comment]
In 'Artifacts' column, click 'View' -> 'Erlang-0.6.SNAPSHOT.zip'. After it's downloaded you can install the plugin from this archive (Settings -> Plugins -> Install plugin from disk...)

**Comment by wmorrison1967** [comment]
Thanks,

**Comment by wmorrison1967** [comment]
Sorry to be a bother,  but I need your help.  I am having issues with rebar
in intellij

I am getting this message: "Information:rebar: Skipped module 'TestModule'
because rebar.config is not found."

I have followed this http://zewaren.net/site/?q=node/144 and
http://ignatov.github.io/intellij-erlang/
without success.  I have been at this for a week and is not out of options.

Regards,
Will

**Comment by deadok22** [comment]
@wmorrison1967 please, file a separate issue for each problem you face. I've created one for you - see #719. For now, you can create an empty rebar.config at your project's root.
