### ISSUE TITLE
WARN - n.process.BaseOSProcessHandler - Must specify non-empty 'commandLine' parameter

### ISSUE THREAD

**Issue by ciez** [ignatov/intellij-erlang#728]
not sure what caused this. It came up while debugging another plugin.

[  22625]   WARN - n.process.BaseOSProcessHandler - Must specify non-empty 'commandLine' parameter 
java.lang.IllegalArgumentException: Must specify non-empty 'commandLine' parameter
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:56)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:58)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:58)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:45)
	at org.intellij.erlang.sdk.ErlangSystemUtil.execute(ErlangSystemUtil.java:70)
	at org.intellij.erlang.sdk.ErlangSystemUtil.getProcessOutput(ErlangSystemUtil.java:60)
	at org.intellij.erlang.sdk.ErlangSystemUtil.getProcessOutput(ErlangSystemUtil.java:43)
	at org.intellij.erlang.dialyzer.ErlangDialyzerExternalAnnotator.doAnnotate(ErlangDialyzerExternalAnnotator.java:95)
	at org.intellij.erlang.dialyzer.ErlangDialyzerExternalAnnotator.doAnnotate(ErlangDialyzerExternalAnnotator.java:49)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.b(ExternalToolPass.java:218)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$500(ExternalToolPass.java:44)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:160)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:282)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ignatov** [comment]
Thanks, please specify the plugin and IDE version.

**Comment by ciez** [comment]
all - latest
Idea 2016.1
Erlang 0.7.876

this warning does not bother me at all. Posted it just in case you'd like to know about it.
