### ISSUE TITLE
IntelliJ IDEA constantly re-indexing

### ISSUE THREAD

**Issue by ant-druha** [ignatov/intellij-erlang#743]
Initially reported to IntelliJ support:

Regularly, IDEA starts looping around a reindex. The log file shows the following which indicates that it is something in the Erlang plugin (which I thought was third-party but given that is is in "your" namespace I'm filing here anyway; regardless, a bad plugin should preferably not crash the whole IDE)

```
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2016.1.3 Build #IU-145.1617.8 
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_76-release 
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2016-06-14 14:23:59,207 [ 95857] ERROR - aemon.impl.PassExecutorService - This method should only be called in unit tests 
java.lang.AssertionError: This method should only be called in unit tests 
at org.intellij.erlang.psi.impl.ErlangFileImpl.getFileTypeForTests(ErlangFileImpl.java:316) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.getFileType(ErlangFileImpl.java:307) 
at org.intellij.erlang.parser.ErlangParserUtil.isApplicationLanguage(ErlangParserUtil.java:40) 
at org.intellij.erlang.parser.ErlangParser.is_app(ErlangParser.java:3646) 
at org.intellij.erlang.parser.ErlangParser.application_file_expression(ErlangParser.java:999) 
at org.intellij.erlang.parser.ErlangParser.forms(ErlangParser.java:2824) 
at org.intellij.erlang.parser.ErlangParser.parse_root_(ErlangParser.java:408) 
at org.intellij.erlang.parser.ErlangParser.parseLight(ErlangParser.java:402) 
at org.intellij.erlang.parser.ErlangParser.parse(ErlangParser.java:18) 
at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:85) 
at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:172) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36) 
at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:141) 
at com.intellij.psi.impl.source.tree.TreeUtil.findFirstLeaf(TreeUtil.java:133) 
at com.intellij.psi.templateLanguages.TemplateDataElementType.a(TemplateDataElementType.java:159) 
at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:93) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.a(LazyParseableElement.java:172) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212) 
at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36) 
at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52) 
at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:810) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$32.process(ErlangFileImpl.java:847) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.processChildrenDummyAware(ErlangFileImpl.java:855) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.collectChildrenDummyAware(ErlangFileImpl.java:830) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.calcAttributes(ErlangFileImpl.java:775) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.access$600(ErlangFileImpl.java:54) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$6.computeValue(ErlangFileImpl.java:100) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$6.computeValue(ErlangFileImpl.java:96) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$ValueProvider.compute(ErlangFileImpl.java:869) 
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49) 
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222) 
at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66) 
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.getAttributes(ErlangFileImpl.java:508) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.getCompileDirectiveExpressions(ErlangFileImpl.java:392) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.containsCompileDirectiveWithOption(ErlangFileImpl.java:462) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.calcExportAll(ErlangFileImpl.java:496) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.access$1600(ErlangFileImpl.java:54) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$21.computeValue(ErlangFileImpl.java:249) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$21.computeValue(ErlangFileImpl.java:245) 
at org.intellij.erlang.psi.impl.ErlangFileImpl$ValueProvider.compute(ErlangFileImpl.java:869) 
at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49) 
at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222) 
at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:66) 
at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38) 
at org.intellij.erlang.psi.impl.ErlangFileImpl.isExportedAll(ErlangFileImpl.java:458) 
at org.intellij.erlang.stubs.ErlangFileStub.<init>(ErlangFileStub.java:37) 
at org.intellij.erlang.stubs.types.ErlangFileElementType$1.createStubForFile(ErlangFileElementType.java:45) 
at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36) 
at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:99) 
at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:127) 
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:945) 
at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124) 
at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118) 
at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398) 
at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1831) 
at com.intellij.util.indexing.FileBasedIndexImpl$23.run(FileBasedIndexImpl.java:1760) 
at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:510) 
at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1718) 
at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1703) 
at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1684) 
at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1848) 
at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1845) 
at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:80) 
at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47) 
at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1867) 
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:887) 
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:855) 
at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:243) 
at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224) 
at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145) 
at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135) 
at org.jetbrains.plugins.ruby.ruby.lang.psi.indexes.RubyClassModuleNameIndex$1.compute(RubyClassModuleNameIndex.java:35) 
at org.jetbrains.plugins.ruby.ruby.lang.psi.indexes.RubyClassModuleNameIndex$1.compute(RubyClassModuleNameIndex.java:33) 
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962) 
at org.jetbrains.plugins.ruby.ruby.lang.psi.indexes.RubyClassModuleNameIndex.find(RubyClassModuleNameIndex.java:33) 
at org.jetbrains.plugins.ruby.rails.codeInsight.cache.FQNCache.getScopedContainers(FQNCache.java:173) 
at org.jetbrains.plugins.ruby.rails.codeInsight.cache.FQNCache.computeFQNCacheValue(FQNCache.java:122) 
at org.jetbrains.plugins.ruby.rails.codeInsight.cache.FQNCache.get(FQNCache.java:54) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.RubyFQNUtil.findContainersByFQN(RubyFQNUtil.java:84) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.RubyFQNUtil.findContainerByFQN(RubyFQNUtil.java:66) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbol(SymbolUtil.java:130) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbol(SymbolUtil.java:111) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.util.SymbolScopeUtil.processSymbolChildrenInner(SymbolScopeUtil.java:82) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.util.SymbolScopeUtil.access$000(SymbolScopeUtil.java:31) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.util.SymbolScopeUtil$1.compute(SymbolScopeUtil.java:51) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.util.SymbolScopeUtil$1.compute(SymbolScopeUtil.java:47) 
at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112) 
at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.util.SymbolScopeUtil.processSymbolChildren(SymbolScopeUtil.java:47) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbolInHierarchy(SymbolUtil.java:556) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.types.impl.RSymbolTypeImpl.getMemberForName(RSymbolTypeImpl.java:57) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbol(SymbolUtil.java:305) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbol(SymbolUtil.java:240) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbol(SymbolUtil.java:212) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.symbols.structure.SymbolUtil.findSymbolInContext(SymbolUtil.java:458) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.resolveToSymbol(RPsiPolyVariantReferenceBase.java:148) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.resolveToSymbol(RPsiPolyVariantReferenceBase.java:136) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RIdentifierReference.resolveToSymbol(RIdentifierReference.java:36) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.multiResolveInner(RPsiPolyVariantReferenceBase.java:82) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase$MyResolver.resolve(RPsiPolyVariantReferenceBase.java:174) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase$MyResolver.resolve(RPsiPolyVariantReferenceBase.java:169) 
at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:144) 
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167) 
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RPsiPolyVariantReferenceBase.multiResolve(RPsiPolyVariantReferenceBase.java:75) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.resolve.ResolveUtil.resolveToSymbolWithCaching(ResolveUtil.java:157) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.types.TypeInferenceHelper.inferCallType(TypeInferenceHelper.java:202) 
at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RIdentifierImpl.computeType(RIdentifierImpl.java:224) 
at org.jetbrains.plugins.ruby.ruby.lang.psi.impl.variables.RIdentifierImpl.getType(RIdentifierImpl.java:203) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReference.getRefObjectType(RQualifiedReference.java:232) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase.resolveToSymbol(RQualifiedReferenceBase.java:118) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase.multiResolveInner(RQualifiedReferenceBase.java:64) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase$MyResolver.resolve(RQualifiedReferenceBase.java:48) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase$MyResolver.resolve(RQualifiedReferenceBase.java:43) 
at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:144) 
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167) 
at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159) 
at org.jetbrains.plugins.ruby.ruby.codeInsight.references.RQualifiedReferenceBase.multiResolve(RQualifiedReferenceBase.java:55) 
at org.jetbrains.plugins.ruby.ruby.lang.findUsages.RubyTargetElementEvaluator.getElementByReference(RubyTargetElementEvaluator.java:59) 
at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:398) 
at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:380) 
at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:247) 
at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:216) 
at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91) 
at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70) 
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444) 
at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178) 
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435) 
at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446) 
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54) 
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432) 
at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408) 
at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206) 
at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260) 
at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858) 
at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687) 
at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642) 
at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

I did disable the Erlang plugin and it didn't happen again. 

Still, it'd be nice if IDEA would be more resilient against plugins acting up :)

**Comment by javadba** [comment]
I have the scala plugin and not the Erlang plugin. Reindexing is happening way too frequently - even if I do not change anything in the pom.xml / build.sbt.

This is a big problem for me because one of my projects is Spark. Imagine the damage that does to me when it happens many times in a day.

This is new behavior for IJ 16 afaict.  It was not happening in earlier versions.

**Comment by javadba** [comment]
I see the following in the log at the time.

2016-06-23 21:19:23,465 [171852953]   INFO - il.indexing.FileBasedIndexImpl - Rebuild requested for index Stubs 
java.lang.Throwable: java.io.EOFException
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleRebuild(FileBasedIndexImpl.java:1313)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1020)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1081)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:945)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:93)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:50)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:694)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:71)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:52)
	at com.intellij.psi.stubs.StubIndexImpl$1.process(StubIndexImpl.java:232)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:593)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:581)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:81)
	at com.intellij.psi.stubs.StubIndexImpl.a(StubIndexImpl.java:258)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.cachedFun$macro$261$1(ScalaPsiManager.scala:192)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.getJavaPackageClassNamesCached(ScalaPsiManager.scala:189)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.getJavaPackageClassNames(ScalaPsiManager.scala:186)
	at org.jetbrains.plugins.scala.finder.ScalaClassFinder.getClassNames(ScalaClassFinder.scala:66)
	at org.jetbrains.plugins.scala.finder.ScalaClassFinder.getClasses(ScalaClassFinder.scala:70)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.getClasses(JavaPsiFacadeImpl.java:278)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.getClassesImpl(ScalaPsiManager.scala:159)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiManager.getClasses(ScalaPsiManager.scala:151)
	at org.jetbrains.plugins.scala.lang.resolve.ResolveUtils$.packageProcessDeclarations(ResolveUtils.scala:543)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScPackageImpl.processDeclarations(ScPackageImpl.scala:62)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReferenceElement$class.processQualifierResolveResult(ResolvableStableCodeReferenceElement.scala:134)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifierResolveResult(ScStableCodeReferenceElementImpl.scala:33)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReferenceElement$class.processQualifier(ResolvableStableCodeReferenceElement.scala:232)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.processQualifier(ScStableCodeReferenceElementImpl.scala:33)
	at org.jetbrains.plugins.scala.lang.resolve.ResolvableStableCodeReferenceElement$class.doResolve(ResolvableStableCodeReferenceElement.scala:189)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.doResolve(ScStableCodeReferenceElementImpl.scala:33)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ImportInfo$.collectAllNamesForWildcard$1(ImportInfo.scala:128)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ImportInfo$.apply(ImportInfo.scala:139)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer$$anonfun$createInfo$1.apply(ScalaImportOptimizer.scala:707)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer$$anonfun$createInfo$1.apply(ScalaImportOptimizer.scala:707)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer$.createInfo(ScalaImportOptimizer.scala:707)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$$anonfun$8.apply(ScImportsHolder.scala:198)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$$anonfun$8.apply(ScImportsHolder.scala:198)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer$$anonfun$collectImportRanges$1.apply(ScalaImportOptimizer.scala:264)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer$$anonfun$collectImportRanges$1.apply(ScalaImportOptimizer.scala:238)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.jetbrains.plugins.scala.editor.importOptimizer.ScalaImportOptimizer.collectImportRanges(ScalaImportOptimizer.scala:238)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$class.addImportsForPaths(ScImportsHolder.scala:198)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.packaging.ScPackagingImpl.addImportsForPaths(ScPackagingImpl.scala:35)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$class.addImportForPath(ScImportsHolder.scala:238)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.packaging.ScPackagingImpl.addImportForPath(ScPackagingImpl.scala:35)
	at org.jetbrains.plugins.scala.lang.psi.ScImportsHolder$class.addImportForClass(ScImportsHolder.scala:136)
	at org.jetbrains.plugins.scala.lang.psi.impl.toplevel.packaging.ScPackagingImpl.addImportForClass(ScPackagingImpl.scala:35)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl$$anonfun$bindToType$1$2.apply(ScStableCodeReferenceElementImpl.scala:178)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl$$anonfun$bindToType$1$2.apply(ScStableCodeReferenceElementImpl.scala:174)
	at org.jetbrains.plugins.scala.lang.psi.api.base.ScReferenceElement$class.safeBindToElement(ScReferenceElement.scala:248)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.safeBindToElement(ScStableCodeReferenceElementImpl.scala:33)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.bindToType$1(ScStableCodeReferenceElementImpl.scala:174)
	at org.jetbrains.plugins.scala.lang.psi.impl.base.ScStableCodeReferenceElementImpl.bindToElement(ScStableCodeReferenceElementImpl.scala:195)
	at org.jetbrains.plugins.scala.annotator.intention.ScalaImportTypeFix$ScalaAddImportAction$$anon$6$$anon$7.run(ScalaImportTypeFix.scala:146)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at org.jetbrains.plugins.scala.util.ScalaUtils$2.run(ScalaUtils.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at org.jetbrains.plugins.scala.util.ScalaUtils.runWriteAction(ScalaUtils.java:135)
	at org.jetbrains.plugins.scala.annotator.intention.ScalaImportTypeFix$ScalaAddImportAction$$anon$6.run(ScalaImportTypeFix.scala:142)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:290)
	at com.intellij.util.io.DataInputOutputUtil.readINT(DataInputOutputUtil.java:44)
	at com.intellij.util.indexing.ValueContainerImpl.readFrom(ValueContainerImpl.java:508)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:95)
	at com.intellij.util.indexing.ValueContainerMap$ValueContainerExternalizer.read(ValueContainerMap.java:78)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:531)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:464)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:118)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:106)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:121)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:82)
	at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:1045)
	at com.intellij.util.indexing.FileBasedIndexImpl$15.convert(FileBasedIndexImpl.java:1035)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1007)
	... 88 more
2016-06-23 21:19:24,303 [171853791]   INFO - il.indexing.FileBasedIndexImpl - scheduleIndexRebuild, reason: checkRebuild 
2016-06-23 21:19:24,581 [171854069]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 8ms; general responsiveness: ok; EDT responsiveness: ok 
2016-06-23 21:19:24,756 [171854244]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 42ms; general responsiveness: ok; EDT responsiveness: ok 
2016-06-23 21:19:24,773 [171854261]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 3ms; general responsiveness: ok; EDT responsiveness: ok 
2016-06-23 21:19:31,908 [171861396]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 7135ms; general responsiveness: 0/20 sluggish, 13/20 very slow; EDT responsiveness: 1/7 sluggish 
2016-06-23 21:19:31,912 [171861400]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 7331ms; general responsiveness: 0/20 sluggish, 13/20 very slow; EDT responsiveness: 1/7 sluggish 
2016-06-23 21:19:31,994 [171861482]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 159002 files to update 
2016-06-23 21:19:31,995 [171861483]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 156368 files to update 
2016-06-23 21:19:32,228 [171861716]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 7472ms; general responsiveness: 0/24 sluggish, 16/24 very slow; EDT responsiveness: 1/8 sluggish 
2016-06-23 21:19:32,391 [171861879]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 161734 files to update 
2016-06-23 21:19:35,263 [171864751]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received. 
2016-06-23 21:19:38,337 [171867825]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received. 
2016-06-23 21:19:41,051 [171870539]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received. 
2016-06-23 21:19:43,772 [171873260]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received. 
2016-06-23 21:19:46,250 [171875738]   INFO - .openapi.util.LowMemoryWatcher - Low memory signal received.

**Comment by ignatov** [comment]
It looks like a bit obsolete.
