### ISSUE TITLE
Missing build errors/warnings in 2018.1

### ISSUE THREAD

**Issue by JakaBac** [ignatov/intellij-erlang#826]
After upgrading to IntelliJ 2018.1 with plugin 0.11.971, build warning and errors are not displayed anymore.
It looks as if the build process completed successfully.

In the build.log the following exception gets logged:
```
2018-03-29 00:07:06,272 [  16803]  ERROR - ecution.process.ProcessHandler - 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.process.ProcessHandler$5.invoke(ProcessHandler.java:223)
	at com.sun.proxy.$Proxy12.onTextAvailable(Unknown Source)
	at com.intellij.execution.process.ProcessHandler.notifyTextAvailable(ProcessHandler.java:197)
	at com.intellij.execution.process.BaseOSProcessHandler$SimpleOutputReader.onTextAvailable(BaseOSProcessHandler.java:212)
	at com.intellij.util.io.BaseOutputReader.sendText(BaseOutputReader.java:202)
	at com.intellij.util.io.BaseOutputReader.processInput(BaseOutputReader.java:186)
	at com.intellij.util.io.BaseOutputReader.readAvailableNonBlocking(BaseOutputReader.java:105)
	at com.intellij.util.io.BaseDataReader.readAvailable(BaseDataReader.java:85)
	at com.intellij.util.io.BaseDataReader.doRun(BaseDataReader.java:163)
	at com.intellij.util.io.BaseDataReader$1$1.run(BaseDataReader.java:66)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:209)
	at com.intellij.util.io.BaseDataReader$1.run(BaseDataReader.java:63)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/intellij/openapi/compiler/CompilerMessageCategory
	at org.intellij.erlang.jps.builder.ErlangCompilerError.createCompilerError(ErlangCompilerError.java:92)
	at org.intellij.erlang.jps.builder.ErlangCompilerError.create(ErlangCompilerError.java:83)
	at org.intellij.erlang.jps.builder.ErlangCompilerProcessAdapter.createCompilerMessage(ErlangCompilerProcessAdapter.java:49)
	at org.intellij.erlang.jps.builder.ErlangCompilerProcessAdapter.onTextAvailable(ErlangCompilerProcessAdapter.java:37)
	... 21 more
```

#825 fixes the issue

**Comment by JakaBac** [comment]
Closed by merging #825
