### ISSUE TITLE
Compile/Run doesn't work with 193

### ISSUE THREAD

**Issue by ignatov** [ignatov/intellij-erlang#898]
```
Error:Internal error: (java.lang.ClassNotFoundException) com.intellij.execution.ExecutionException
java.lang.ClassNotFoundException: com.intellij.execution.ExecutionException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.intellij.erlang.jps.builder.ErlangBuilderService.createBuilders(ErlangBuilderService.java:38)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:55)
	at org.jetbrains.jps.incremental.BuilderRegistry.<init>(BuilderRegistry.java:34)
	at org.jetbrains.jps.incremental.BuilderRegistry$Holder.<clinit>(BuilderRegistry.java:37)
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:135)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

![image](https://user-images.githubusercontent.com/426890/69478220-26fb9700-0e01-11ea-9fe4-a38284e0516f.png)

**Comment by ignatov** [comment]
```
Error:Internal error: (java.lang.NoClassDefFoundError) Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.jps.incremental.BuilderRegistry$Holder
	at org.jetbrains.jps.incremental.BuilderRegistry.getInstance(BuilderRegistry.java:45)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:135)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
