### ISSUE TITLE
2020.2 plugin was working fine, then suddenly I can't type more than one character at the end of a line

### ISSUE THREAD

**Issue by MikeBenza** [ignatov/intellij-erlang#917]
I upgraded to the 2020.2-compatible version of the plugin a few hours ago.  I _think_ I hit some bad key combination and now I can't type anything other than a single character at the end of the line.

1. Start IntelliJ
2. Open project
3. Place cursor anywhere other than the end of a line
4. Type a character: nothing happens
5. Place cursor at end of line
6. Type a character: it appears
7. Type another character: it appears and is immediately erased

I've figured out that I can disable the Erlang plugin and I can use the editor again.

This only applies in the editor.  All other typeable text areas seem to work (find/replace, search in preferences pane).

IntelliJ version: 2020.2
Plugin version: 0.11.1068

**Comment by MikeBenza** [comment]
Something is wrong with working with unterminated strings.  I discovered it when working with this line:

```
?LOG_WARNING(LogCtx, ")")
```

If I have just that line, I can type without any problem.

If I erase the last two characters (i.e. make an unterminated string), I start to have the problem described above.

Once it's in a bad state the solution seems to be one of the following:
* disable the Erlang plugin,
* restart IntelliJ
* terminate the string with a `"`
* enable the plugin
* restart IntelliJ

OR

* restart IntelliJ
* terminate the string with a `"` (because you can type one character at the end of a line)
* save the file
* restart IntelliJ

**Comment by MikeBenza** [comment]
After about 30 minutes of trying to narrow down the parts of the code that were causing the problem, suddenly something changed and I can't reproduce it.  I was gradually eliminating functions, testing it, and seeing if that eliminated code caused the problem.  Each time I got to a point where I could trigger the problem, I backed up the file.  Then suddenly, it started working again and I can't trigger it in the original code, or with any of the backed up files.

**Comment by MikeBenza** [comment]
I encountered this again today.

**Comment by MikeBenza** [comment]
This happened again today with the following lie:

```erl
handle(#{'__erllambda_wrapper' := true, '__queue_name' := QueueName, attributes := Attributes} = Msg0, Context, ParentTCtx) ->
```

The problem was related to the single quotes around the atoms.

**Comment by ignatov** [comment]
Thaks, will try to replicate, could you please attach logs from IDE next time, see https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by SackCastellon** [comment]
Hi, I've started to have the a similar problem, however it seem to only happen in a specific file, the content of which can be found [here](https://gist.github.com/SackCastellon/40f155a04410302bcfb5bec1ba955bb7).


### Video

[Intellij Erlang Bug Video.zip](https://github.com/ignatov/intellij-erlang/files/5336979/Intellij.Erlang.Bug.Video.zip)

The video shows how you can work normally in a new file, but typing two double quotes (a string) in a specific file will prevent you from typing anything else as soon as you type the second double quote. You can only "type" at the end of lines, but whatever you type will be immediately deleted.

### Logs

[log.zip](https://github.com/ignatov/intellij-erlang/files/5336985/log.zip)

### IntelliJ Information
IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: keymap.windows.as.meta=true
Non-Bundled Plugins: org.jetbrains.erlang, name.kropp.intellij.makefile

**Comment by kvakvs** [comment]
Happens often when i start typing a log-format macro `?liof(` when opening the string, it seems to suddenly break with this log below. After this happened no editor typing and deleting works, only copy and paste. Full IDE restart fixes the problem until I touch quoted string in the macro again.

```
2020-10-09 05:10:43,578 [3221857]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.2.3  Build #IU-202.7660.26 
2020-10-09 05:10:43,579 [3221858]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-10-09 05:10:43,579 [3221858]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2020-10-09 05:10:43,579 [3221858]  ERROR - llij.ide.plugins.PluginManager - Last Action: EditorBackSpace 
2020-10-09 05:10:44,942 [3223221]  ERROR - llij.ide.plugins.PluginManager - Unexpected reentrancy of DefaultRawTypedHandler 
java.lang.IllegalStateException: Unexpected reentrancy of DefaultRawTypedHandler
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:41)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:275)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:183)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:183)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1322)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1305)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3408)
	at com.intellij.openapi.editor.impl.EditorImpl$8.keyTyped(EditorImpl.java:1146)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6609)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6431)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:878)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1148)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1017)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:843)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:41)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4910)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:894)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:835)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by stephb9959** [comment]
I can confirm that I have the same problem. I tried disabling every other plugin, except for ErlIDE, and I still get the problem. I have been trying to type the same double quote for 20 minutes.

**Comment by alvaropag** [comment]
I have the same problem, caused inside a double quote string.

**Comment by ignatov** [comment]
Ouch, that issue looks nasty, will look into, thanks for reporting.

**Comment by ignatov** [comment]
@SackCastellon thanks for the repro.

**Comment by ignatov** [comment]
I've just uploaded a new build with a fix. Please consider updating, and sorry for the inconvenience.
https://plugins.jetbrains.com/plugin/7083-erlang/versions/stable/100084
