### ISSUE TITLE
unresolved include

### ISSUE THREAD

**Issue by WilliamWei1989** [ignatov/intellij-erlang#931]
![image](https://user-images.githubusercontent.com/10206504/101604757-5432db80-3a3c-11eb-83ba-97e7990d457e.png)
the file in the project  cannot be found。The problem appears in Goland,。It is OK in Intellij IDEA。Why？

**Comment by ignatov** [comment]
Hi, is there any chance to see your project or a small reproducible demo?

**Comment by DmytroYakubovskyi** [comment]
I had the same issue after each upgrade on IDEA Ultimate. 
Project SDK was set up correctly, but project itself wasn't marked as an erlang like. Try to:
Project structure -> Modules -> remove root module (your current project) and reimport again. 
Also do not try to reuse IDEA configuration file. Looks like it's not fully compatible between different versions, corrupted or something.

**Comment by kubantsev** [comment]
1. Find single include file doesn't work as described above, none errors logged.
2. Selecting from multiple include files doesn't select any at all:
```
2021-03-24 10:29:25,787 [89203802]  ERROR - llij.ide.plugins.PluginManager - Module source root type org.intellij.erlang.jps.model.ErlangIncludeSourceRootType@5fa8c8a4 is not registered as JpsModelSerializerExtension 
java.lang.IllegalStateException: Module source root type org.intellij.erlang.jps.model.ErlangIncludeSourceRootType@5fa8c8a4 is not registered as JpsModelSerializerExtension
        at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:57)
        at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:204)
        at com.intellij.workspaceModel.ide.impl.legacyBridge.module.roots.ModifiableContentEntryBridge.addSourceFolder(ModifiableContentEntryBridge.kt:195)
        at org.intellij.erlang.roots.ErlangIncludeDirectoryUtil.markAsIncludeDirectory(ErlangIncludeDirectoryUtil.java:48)
        at org.intellij.erlang.roots.ErlangIncludeDirectoryUtil.markAsIncludeDirectory(ErlangIncludeDirectoryUtil.java:58)
        at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix.fixUsingIncludeFile(ErlangFindIncludeQuickFix.java:228)
        at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix$1.lambda$onChosen$0(ErlangFindIncludeQuickFix.java:169)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1000)
        at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix$1.lambda$onChosen$1(ErlangFindIncludeQuickFix.java:168)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
        at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:158)
        at org.intellij.erlang.quickfixes.ErlangFindIncludeQuickFix$1.onChosen(ErlangFindIncludeQuickFix.java:168)
        at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:412)
        at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:359)
        at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:272)
        at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:376)
        at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:356)
        at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
        at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
        at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:93)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:810)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-03-24 10:29:25,787 [89203802]  ERROR - llij.ide.plugins.PluginManager - WebStorm 2020.3.3  Build #WS-203.7717.59 
2021-03-24 10:29:25,792 [89203807]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-03-24 10:29:25,792 [89203807]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2021-03-24 10:29:25,792 [89203807]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Erlang version: 0.11.1085 
2021-03-24 10:29:25,792 [89203807]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowIntentionActions
```
